### ISSUE TITLE
请问下作者getPostFull这个接口是什么功能，现在还能使用吗？

### ISSUE THREAD

**Issue by zer0e** [lhllhx/miyoubi#2]
`https://api-takumi.mihoyo.com/post/wapi/getPostFull?gids=1&post_id=`

**Comment by lhllhx** [comment]
所有接口都能正常使用，这个为完成阅读帖子任务的api

**Comment by zer0e** [comment]
因为返回了403我以为已经失效了

**Comment by lhllhx** [comment]
请注意你的请求头是否正确，未发现这种情况

**Comment by zer0e** [comment]
好的 多谢
