### ISSUE TITLE
请求头需要DS

### ISSUE THREAD

**Issue by 2314933036** [lhllhx/miyoubi#3]
否则报
{"data":null,"message":"请求异常","retcode":-401}

header需要添加
'DS': '1599549848,ho44h1,cf96f942415e42c2c149eaf2bd133b59,7d07ffd9d7816ae7926858b73f01bf6b',

暂时未知加密算法类型

**Comment by lhllhx** [comment]
mhy又加密了啊。。。 我最近忙开学没空。。。 如果有解决方案或建议的话，提交一下pr或者在这里回复

**Comment by 2314933036** [comment]
我在尝试反编译米水社apk,混淆过的代码看的我头都大了,目前可以确定的是md5加密

**Comment by 2314933036** [comment]
![image](https://user-images.githubusercontent.com/38069007/92678639-1351fa80-f359-11ea-83a3-156d20f22bd8.png)

**Comment by lhllhx** [comment]
> 我在尝试反编译米水社apk,混淆过的代码看的我头都大了,目前可以确定的是md5加密

请问有办法弄出具体算法吗

**Comment by 2314933036** [comment]
> > 我在尝试反编译米水社apk,混淆过的代码看的我头都大了,目前可以确定的是md5加密
> 
> 请问有办法弄出具体算法吗

现在已知是加盐md5具体算法在so包内,然鹅so包我不会弄(

**Comment by jianggaocheng** [comment]
将 header 的 x-rpc-client_type 改成一些错误的值，比如888可以绕过 DS 的检查，但是这样只有签到接口可以获取米游币，阅读帖子、点赞不会产生米游币（论坛等级可以提升，米游币任务没有进度）

通过重放请求，发现DS并没有包含请求参数的MD5，篡改url的postid可以成功完成米游币任务。

看来下一步的关键就是破解 DS 的算法
@2314933036 不知道你那里有没有进展

**Comment by 2314933036** [comment]
> 将 header 的 x-rpc-client_type 改成一些错误的值，比如888可以绕过 DS 的检查，但是这样只有签到接口可以获取米游币，阅读帖子、点赞不会产生米游币（论坛等级可以提升，米游币任务没有进度）
> 
> 通过重放请求，发现DS并没有包含请求参数的MD5，篡改url的postid可以成功完成米游币任务。
> 
> 看来下一步的关键就是破解 DS 的算法
> @2314933036 不知道你那里有没有进展

4个参数目前只知道第一个和最后一个，so包我实在无能为力了，用了ida根本看不懂

**Comment by jianggaocheng** [comment]
目前对算法的推断是每一种 x-rpc-client_type 对应一种不同的签名算法，
【iOS】x-rpc-client_type = 1 
【Android】x-rpc-client_type = 2
这两种 x-rpc-client_type 需要验证 DS 的值，并且目前抓包下来看两种平台的签名算法是不一样的

【web】x-rpc-client_type = 4
通过debug 逆向得到签名算法 "MD5(salt=MD5(2.1.0)&t=时间戳&r=6位随机字符数字)”

**Comment by 2314933036** [comment]
> 目前对算法的推断是每一种 x-rpc-client_type 对应一种不同的签名算法，
> 【iOS】x-rpc-client_type = 1 
> 【Android】x-rpc-client_type = 2
> 这两种 x-rpc-client_type 需要验证 DS 的值，并且目前抓包下来看两种平台的签名算法是不一样的
> 
> 【web】x-rpc-client_type = 4
> 通过debug 逆向得到签名算法 "MD5(salt=MD5(2.1.0)&t=时间戳&r=6位随机字符数字)”

dalao加油

**Comment by 2314933036** [comment]
`def get_DS():
    t = int(time.time())
    a = "".join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 6))
    b = ""
    c = hashlib.md5(f"d7d38ba4719a2dfc6ec10c956733a8f4com.mihoyo.hyperion2.1.0{t}".encode(encoding="utf-8")).hexdigest()
    return f"{t},{a},{b},{c}"`

**Comment by 2314933036** [comment]
> `def get_DS(): t = int(time.time()) a = "".join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 6)) b = "" c = hashlib.md5(f"d7d38ba4719a2dfc6ec10c956733a8f4com.mihoyo.hyperion2.1.0{t}".encode(encoding="utf-8")).hexdigest() return f"{t},{a},{b},{c}"`

git发代码怎么就这么别扭呢
def get_DS():
    t = int(time.time())
    a = "".join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 6))
    b = ""
    c = hashlib.md5(f"d7d38ba4719a2dfc6ec10c956733a8f4com.mihoyo.hyperion2.1.0{t}".encode(encoding="utf-8")).hexdigest()
    return f"{t},{a},{b},{c}"

**Comment by lhllhx** [comment]
善用markdown的代码模式
```python
def get_DS():
    t = int(time.time())
    a = "".join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 6))
    b = ""
    c = hashlib.md5(f"d7d38ba4719a2dfc6ec10c956733a8f4com.mihoyo.hyperion2.1.0{t}".encode(encoding="utf-8")).hexdigest()
    return f"{t},{a},{b},{c}"
```

**Comment by jianggaocheng** [comment]
@2314933036 厉害了，看来你已经把 libaab.so 里面的两个方法解出来了 com.mihoyo.hyperion 我在 so 里面也看到了，前面那个 d7d38ba4719a2dfc6ec10c956733a8f4 是怎么来的方便分享下思路吗.

**Comment by 2314933036** [comment]
> @2314933036 厉害了，看来你已经把 libaab.so 里面的两个方法解出来了 com.mihoyo.hyperion 我在 so 里面也看到了，前面那个 d7d38ba4719a2dfc6ec10c956733a8f4 是怎么来的方便分享下思路吗.

是某位dalao弄得(

**Comment by jianggaocheng** [comment]
中间的第三节的算法是
```
  let randomStr = randomString(6);
  let timestamp = Math.floor(Date.now() / 1000)
  let appVersion = "2.1.0";

  let sign1 = md5(`salt=b253c83ab2609b1b600eddfe974df47b&t=${timestamp}&r=${randomStr}`)
  let sign2 = md5(`d7d38ba4719a2dfc6ec10c956733a8f4com.mihoyo.hyperion2.1.0${timestamp}`);

  // 1602476146,jj0n79,390e6b62002cf16f20bec30de5c28c2c,cc73a67900acb36da93bc4494014e3a4

  return {
    'Cookie': stringifyCookie(cookieData),
    'Content-Type': 'application/json',
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36',
    'Origin' : 'https://bbs.mihoyo.com',
    'x-rpc-app_version': '2.1.0',
    'x-rpc-client_type': '2',
    'DS': `${timestamp},${randomStr},${sign1},${sign2}`
  }
```

因为我用 js 比较多，用 node 重写了个脚本 https://github.com/jianggaocheng/mihoyo-signin

**Comment by 2314933036** [comment]
> 中间的第三节的算法是
> 
> ```
>   let randomStr = randomString(6);
>   let timestamp = Math.floor(Date.now() / 1000)
>   let appVersion = "2.1.0";
> 
>   let sign1 = md5(`salt=b253c83ab2609b1b600eddfe974df47b&t=${timestamp}&r=${randomStr}`)
>   let sign2 = md5(`d7d38ba4719a2dfc6ec10c956733a8f4com.mihoyo.hyperion2.1.0${timestamp}`);
> 
>   // 1602476146,jj0n79,390e6b62002cf16f20bec30de5c28c2c,cc73a67900acb36da93bc4494014e3a4
> 
>   return {
>     'Cookie': stringifyCookie(cookieData),
>     'Content-Type': 'application/json',
>     'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36',
>     'Origin' : 'https://bbs.mihoyo.com',
>     'x-rpc-app_version': '2.1.0',
>     'x-rpc-client_type': '2',
>     'DS': `${timestamp},${randomStr},${sign1},${sign2}`
>   }
> ```
> 
> 因为我用 js 比较多，用 node 重写了个脚本 https://github.com/jianggaocheng/mihoyo-signin

看了你这个突然发现算法在挺前面的,我一直在找后面的东西
![image](https://user-images.githubusercontent.com/38069007/96085118-e7470d80-0ef2-11eb-84ee-b10701be1a19.png)

**Comment by lhllhx** [comment]
提醒一下 @jianggaocheng  请求头千万不要漏参数了，mhy在这种地方可是真·闲的蛋疼的去检测
过几天我尽量把这我一坨代码重构一下（当初真的瞎jb写），尽量把各种反爬安排上（比如设备id随机化什么的）

**Comment by jianggaocheng** [comment]
@lhllhx 谢谢提醒，
是 'x-rpc-xxxx' 这些吧，mhy 看来还真是闲的。。。

**Comment by inky-s** [comment]
为各位大佬打call点赞~！

受到原神签到领甜甜鸡repo的启发在你们讨论的基础上码了个Github workflow版本：https://github.com/inky-s/myb_workflow

**Comment by ddd-zero** [comment]
https://github.com/lhllhx/miyoubi/issues/3#issuecomment-708992569
啥B米哈游，今天我做签到脚本也遇到这个问题了。

**Comment by Kikyo18** [comment]
> @lhllhx 谢谢提醒，
> 是 'x-rpc-xxxx' 这些吧，mhy 看来还真是闲的。。。



> 提醒一下 @jianggaocheng 请求头千万不要漏参数了，mhy在这种地方可是真·闲的蛋疼的去检测
> 过几天我尽量把这我一坨代码重构一下（当初真的瞎jb写），尽量把各种反爬安排上（比如设备id随机化什么的）

啥B米哈游，今天我做签到脚本也遇到这个问题了。
